backend:
  name: git-gateway
  # name: test-repo
  branch: main # Branch to update (optional; defaults to master)
media_folder: public/static/img
public_folder: static/uploads
logo_url: public/img/netliheart.svg
collections:
  - name: "screens"
    label: "Screens"
    files:
    - label: "Home"
      name: "home"
      file: "content/home.md"
      fields:
        - { label: "Title", name: "title", widget: "string"}
        - { label: "Publish Date", name: "date", widget: "datetime" }
        - { label: "Body", name: "body", widget: "markdown"}
        - label: 'Projects'
          name: "projects"
          widget: list
          fields:
            - { label: "Name", name: "name", widget: "string"}
            - { label: "Description", name: "description", widget: "text"}